version: '2.4'

services:
  bionic:
    build:
      context: .
      dockerfile: bionic/Dockerfile
    image: interaction/buildpack-deps:bionic
  focal:
    build:
      context: .
      dockerfile: focal/Dockerfile
    image: interaction/buildpack-deps:focal
  jammy:
    build:
      context: .
      dockerfile: jammy/Dockerfile
    image: interaction/buildpack-deps:jammy
  latest:
    build:
      context: .
      dockerfile: jammy/Dockerfile
    image: interaction/buildpack-deps:latest
