version: '2.4'

services:
  bionic:
    build: bionic
    image: interaction/buildpack-deps:bionic
  focal:
    build: focal
    image: interaction/buildpack-deps:focal
  latest:
    build: focal
    image: interaction/buildpack-deps:latest
