name: ci

on:
  push:
    branches:
      - multiarch

jobs:
  image:
    runs-on:
      - ${{ matrix.arch }}
      - linux
      - self-hosted
    env:
      DOCKER_REPO: interaction/buildpack-deps
    strategy:
      matrix:
        arch:
          - arm64
          - x64
        os:
          - bionic
          - focal
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.os }}/Dockerfile
          push: true
          tags: ${{ env.REPO }}:sha-${{ github.sha }}-${{ matrix.os }}-${{ matrix.arch }}

  manifest:
    runs-on:
      - linux
      - self-hosted
    needs: image
    env:
      DOCKER_REPO: interaction/buildpack-deps
    strategy:
      matrix:
        os:
          - bionic
          - focal
    steps:
      # This action transforms ${{ git.ref }} from `refs/heads/<branch_name>` to
      # `${{ env.DOCKER_REPO }}:<branch_name>`. It must return a single tag.
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.DOCKER_REPO }}
          tag-latest: false

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and Push Manifest List (Branch)
        run: |
          docker manifest create ${{ steps.docker_meta.outputs.tags }}-${{ matrix.os }} \
            --amend ${{ env.DOCKER_REPO }}:sha-${{ github.sha }}-${{ matrix.os }}-arm64 \
            --amend ${{ env.DOCKER_REPO }}:sha-${{ github.sha }}-${{ matrix.os }}-x64
          docker manifest push ${{ steps.docker_meta.outputs.tags }}-${{ matrix.os }}

      - name: Create and Push Manifest List (SHA)
        run: |
          docker manifest create ${{ env.DOCKER_REPO }}:sha-${{ github.sha }}-${{ matrix.os }} \
            --amend ${{ env.DOCKER_REPO }}:sha-${{ github.sha }}-${{ matrix.os }}-arm64 \
            --amend ${{ env.DOCKER_REPO }}:sha-${{ github.sha }}-${{ matrix.os }}-x64
          docker manifest push ${{ env.DOCKER_REPO }}:sha-${{ github.sha }}-${{ matrix.os }}

  readme:
    runs-on:
      - self-hosted
    needs: manifest
      - name: Update README
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: interaction/buildpack-deps
