name: Continuous Integration

on:
  push:
    branches: '*'
  schedule:
    - cron:  '0 17 * * *'

jobs:
  image:
    runs-on:
      - ${{ matrix.arch }}
      - linux
      - self-hosted
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.os }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPO }}:sha-${{ github.sha }}-${{ matrix.os }}-${{ matrix.arch }}
    strategy:
      matrix:
        arch:
          - arm64
          - x64
        os:
          - bionic
          - focal

  manifest:
    needs: image
    runs-on:
      - linux
      - self-hosted
    steps:
      # Transform ${{ git.ref }} from `refs/heads/<branch_name>` to `${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPO }}:<branch_name>`.
      - name: Docker Meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPO }}
          tag-latest: false
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create and Push Manifest List (Branch)
        run: |
          docker manifest create ${{ steps.docker_meta.outputs.tags }}-${{ matrix.os }} \
            --amend ${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPO }}:sha-${{ github.sha }}-${{ matrix.os }}-arm64 \
            --amend ${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPO }}:sha-${{ github.sha }}-${{ matrix.os }}-x64
          docker manifest push ${{ steps.docker_meta.outputs.tags }}-${{ matrix.os }}
      - name: Create and Push Manifest List (SHA)
        run: |
          docker manifest create ${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPO }}:sha-${{ github.sha }}-${{ matrix.os }} \
            --amend ${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPO }}:sha-${{ github.sha }}-${{ matrix.os }}-arm64 \
            --amend ${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPO }}:sha-${{ github.sha }}-${{ matrix.os }}-x64
          docker manifest push ${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPO }}:sha-${{ github.sha }}-${{ matrix.os }}
    strategy:
      matrix:
        os:
          - bionic
          - focal
